// src/app/layout.tsx 
import "./globals.css";
import Layout from "./components/layout/Layout";
import { AuthProvider } from "./hooks/useAuthContext";
import { NoteProvider } from "./hooks/useNotesData";
import { AuthGuard } from "./components/AuthGuard";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AuthGuard>
            <NoteProvider>
              <Layout>{children}</Layout>
            </NoteProvider>
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
