// frontend/src/app/RootLayout.tsx
import type { Metadata } from "next";
// ----------------------------------------------------
// 修正点1: Geistの代わりに、Google FontsのInterとRoboto_Monoをインポート
// ----------------------------------------------------
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Sidebar from "./components/layout/Sidebar";
import MainContent from "./components/layout/MainContent";

// ----------------------------------------------------
// 修正点2: フォントローダーの変数名と設定をGoogle Fontsに合わせる
// ----------------------------------------------------
const inter = Inter({
  subsets: ["latin"],
  // CSS変数名（--font-geist-sans）をInterに適用
  variable: "--font-geist-sans",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  // CSS変数名（--font-geist-mono）をRoboto_Monoに適用
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* ---------------------------------------------------- */}
      {/* 修正点3: bodyタグにフォントのクラスを適用する（variableプロパティを使用） */}
      {/* ---------------------------------------------------- */}
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <Header />
        <div className="flex flex-1">
          <Sidebar />
          <MainContent>{children}</MainContent>
        </div>
      </body>
    </html>
  );
}
